[package]
name = "Rust-epsilon-dev-template"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
embedded-alloc = "0.6.0"
enum-iterator = "2.3.0"

[build-dependencies]
cc = "1.2.46"
