[target.thumbv7em-none-eabihf]
runner = 'npm exec --yes -- nwlink@0.0.19 install-nwa'
rustflags = ["-C", "link-arg=--relocatable", "-C", "link-arg=-no-gc-sections", "-C", "link-arg=-lstorage_c"]

[target.'cfg(target_os="macos")']
rustflags = [
    "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup", "-C", "link-arg=-lSystem"
]

[target.'cfg(target_os="linux")']
rustflags = [
    "-C", "link-arg=-Wl,-undefined,dynamic_lookup", "-C", "link-arg=-Wl,-z,undefs"
]

[build]
target = "thumbv7em-none-eabihf"